### ISSUE TITLE
logtail-python makes a new http connection every upload batch

### ISSUE THREAD

**Issue by 12932** [logtail/logtail-python#1]
Is this by design?

https://github.com/logtail/logtail-python/blob/master/logtail/uploader.py#L18

It seems quite wasteful to keep creating a new HTTP connection every time an upload batch occurs, the `requests` library has a very helpful `session` object which will automatically re-use the same http connection, `requests.Session()`

**Comment by gyfis** [comment]
Thanks for the report! This will be fixed in #2
