### ISSUE TITLE
Cannot use the logger in a FastAPI application

### ISSUE THREAD

**Issue by slavovthinks** [logtail/logtail-python#12]
My issue is the same as the one from here: https://stackoverflow.com/questions/74605213/python-fastapi-uvicorn-external-logger-wont-work

**Comment by curusarn** [comment]
Hi @slavovthinks,

I appreciate your patience! Thanks for reaching out.

We have stopped using `_is_main_process` in version [v0.2.0](https://github.com/logtail/logtail-python/releases/tag/v0.2.0), which should solve your issue. 

Could you update to [v0.2.0](https://github.com/logtail/logtail-python/releases/tag/v0.2.0) and let me know if the issue persists? 🙏

Thanks again for your report and the workaround.


Best,

Simon

**Comment by curusarn** [comment]
I'm closing this since the issue was fixed and should no longer happen.

Feel free to reopen if you are still encountering the issue.
