### ISSUE TITLE
SystemExit exception by flusher reported by monitoring tools

### ISSUE THREAD

**Issue by Nnonexistent** [logtail/logtail-python#18]
I have a FastAPI application with both sentry and logtail. Sentry has a ThreadingIntegration, which reports all unhandled exceptions in threads. And logtail finishes flusher thread with [`sys.exit(0)`](https://github.com/logtail/logtail-python/blob/master/logtail/flusher.py#L71), which is then reported by sentry, which is quite annoying.

If you think it's reasonable to change this logtail behavior to just finish flusher thread silently, I could create a PR for that.

**Comment by curusarn** [comment]
Hi @Nnonexistent,
Thank you for raising this!

I don't see any issue with finishing the flusher without `sys.exit(0)`. You are welcome to submit a PR.
Thanks for the initiative!
